# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Analyze package

on:
  push:
    paths:
      - 'pkgs.txt'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install aapt
      run: sudo apt-get update && sudo apt-get install -y aapt

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Run
      run: |
        uvx playwright install firefox --with-deps
        for f in $(git diff HEAD^1 -- pkgs.txt | grep ^+http | tr -d '+'); do
          echo $f;
          uv run main.py --url "$f"
        done


    - name: Commit
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git status --porcelain
        timestamp=$(date -u)
        git add apps.csv manifests
        git commit -m "Update: ${timestamp}" || exit 0
        git push origin ${{ github.ref_name }}
