# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "run" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install aapt
      run: sudo apt-get update && sudo apt-get install -y aapt

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Run
      run: |
        uvx playwright install firefox --with-deps
        uv run main.py

    - name: Commit
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        timestamp=$(date -u)
        branch_name=$(date +%s)
        git checkout -b $branch_name
        echo branch_name=$branch_name >> GITHUB_ENV
        git add -A
        git commit -m "Latest data: ${timestamp}" || exit 0


    - name: create pull request
      run: gh pr create -B main -H "$branch_name" --head --title "Merge $branch_name" --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
